Update patch set 2
Patch Set 2:

> Uploaded patch set 1.

@steve:

latest property import cause crashes:
Need to hack some apks

08-13 22:10:17.543  4838  4838 D AndroidRuntime: Shutting down VM
08-13 22:10:17.545  4838  4838 E AndroidRuntime: FATAL EXCEPTION: main
08-13 22:10:17.545  4838  4838 E AndroidRuntime: Process: com.qti.dpmserviceapp, PID: 4838
08-13 22:10:17.545  4838  4838 E AndroidRuntime: Theme: themes:{}
08-13 22:10:17.545  4838  4838 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/qti/location/sdk/IZatManager;
08-13 22:10:17.545  4838  4838 E AndroidRuntime: 	at com.qti.dpm.DpmNsrmBackgroundEventHdlr.initialize(DpmNsrmBackgroundEventHdlr.java:346)
08-13 22:10:17.545  4838  4838 E AndroidRuntime: 	at com.qti.dpm.DpmNsrmBackgroundEventHdlr.<init>(DpmNsrmBackgroundEventHdlr.java:303)
08-13 22:10:17.545  4838  4838 E AndroidRuntime: 	at com.qti.dpm.DpmNsrm.<init>(DpmNsrm.java:46)
08-13 22:10:17.545  4838  4838 E AndroidRuntime: 	at com.qti.dpm.DpmService.initNsrm(DpmService.java:982)
08-13 22:10:17.545  4838  4838 E AndroidRuntime: 	at com.qti.dpm.DpmService.Initialize(DpmService.java:977)
08-13 22:10:17.545  4838  4838 E AndroidRuntime: 	at com.qti.dpmserviceapp.DpmServiceApp.onCreate(DpmServiceApp.java:35)
08-13 22:10:17.545  4838  4838 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2911)
08-13 22:10:17.545  4838  4838 E AndroidRuntime: 	at android.app.ActivityThread.-wrap4(ActivityThread.java)
08-13 22:10:17.545  4838  4838 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1446)
08-13 22:10:17.545  4838  4838 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-13 22:10:17.545  4838  4838 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
08-13 22:10:17.545  4838  4838 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5461)
08-13 22:10:17.545  4838  4838 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-13 22:10:17.545  4838  4838 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
08-13 22:10:17.545  4838  4838 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
08-13 22:10:17.545  4838  4838 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.qti.location.sdk.IZatManager" on path: DexPathList[[zip file "/system/framework/com.qti.dpmframework.jar", zip file "/system/priv-app/dpmserviceapp/dpmserviceapp.apk"],nativeLibraryDirectories=[/system/priv-app/dpmserviceapp/lib/arm64, /system/priv-app/dpmserviceapp/dpmserviceapp.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]
08-13 22:10:17.545  4838  4838 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
08-13 22:10:17.545  4838  4838 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
08-13 22:10:17.545  4838  4838 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
08-13 22:10:17.545  4838  4838 E AndroidRuntime: 	... 15 more
08-13 22:10:17.545  4838  4838 E AndroidRuntime: 	Suppressed: java.lang.ClassNotFoundException: com.qti.location.sdk.IZatManager
08-13 22:10:17.545  4838  4838 E AndroidRuntime: 		at java.lang.Class.classForName(Native Method)
08-13 22:10:17.545  4838  4838 E AndroidRuntime: 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
08-13 22:10:17.545  4838  4838 E AndroidRuntime: 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
08-13 22:10:17.545  4838  4838 E AndroidRuntime: 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
08-13 22:10:17.545  4838  4838 E AndroidRuntime: 		... 16 more

Patch-set: 2
Reviewer: chenxi.mao <10151@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Verified=0