Update patch set 2
Patch Set 2:

Grarak's blobs? So the stock blobs? I tried with the modified one from dianlujitao, but now I got "java.lang.NoClassDefFoundError: Failed resolution of: Landroid/util/OpFeatures;". :/

Patch-set: 2